import Header from "@/components/Header";
import React from "react";
import "./globals.css";

export const metadata = {
    title: "Beautiful Images",
    description: "Generated by Next.js",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body>
                <main className="w-full min-h-screen h-auto flex flex-col items-center justify-start bg-white">
                    <Header />
                    {children}
                </main>
            </body>
        </html>
    );
}
